# Generated by Django 6.0.4 on 2026-04-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtpmail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='emaillog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Store error message if email sending fails', null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='smtp_config_id',
            field=models.PositiveBigIntegerField(default=1, help_text='ID of the SMTP configuration used for this email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('QUEUE', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='QUEUE', max_length=20),
        ),
    ]
