# Generated by Django 6.0.4 on 2026-04-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtpmail', '0002_alter_emaillog_options_emaillog_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpconfig',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
