# Generated by Django 6.0.4 on 2026-04-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtpmail', '0003_alter_smtpconfig_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpconfig',
            name='use_ssl',
            field=models.BooleanField(default=False, help_text='Use Implicit SSL (usually port 465)'),
        ),
        migrations.AlterField(
            model_name='smtpconfig',
            name='use_tls',
            field=models.BooleanField(default=True, help_text='Use STARTTLS (usually port 587)'),
        ),
    ]
